### ISSUE TITLE
Taboola widget rendering timed out

### ISSUE THREAD

**Issue by prabuscs** [taboola/taboola-ios#11]

**Comment by Chronocore** [comment]
I have this error message also. What is the reason for this error message?

This Error appears on iPhone with iOS 9, but not iOS 10+
And now also on iPads with iOS 10 and 11! (iOS 9 not needed in this case)
I will test iOS 12 on iPad tomorrow.

**Comment by Chronocore** [comment]
On iPad with iOS12 I have the same problem.
So, at the moment, I can't make any Taboola Ads visible on screen.

**Comment by omriariav** [comment]
@Chronocore we have moved our documentation and support forum to https://sdk.taboola.com this repo is no longer maintained
