### ISSUE TITLE
Delegate method naming scheme disregards common iOS conventions

### ISSUE THREAD

**Issue by ortekka** [taboola/taboola-ios#4]
This delegate method discussed in the documentation:

`- (BOOL)taboolaViewItemClickHandler:(NSString *)pURLString :(BOOL)isOrganic;`

uses a *keywordless* parameter, which while technically accepted by Objective-C compilers, goes against common Objective-C conventions and is officially frowned upon by Apple. See:

https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html

And particularly the point where it recommends to *Use keywords before all arguments*.

Also, the first parameter of a delegate method should always be the object that it sending the message. In this case, it should be the `TaboolaView` object. Again, this is a pervasive convention in the iOS community, and one that is officially sanctioned by Apple. See the above document again where it says: *Start the name by identifying the class of the object that’s sending the message*.

A better name for the above method would be this:

`- (BOOL)taboolaView:(TaboolaView*)taboolaView didClickRecommendation:(NSURL*)recommendationURL isOrganic:(BOOL)isOrganic;`

**Comment by omriariav** [comment]
@ortekka thank you, we have moved our documentation and support forum to https://sdk.taboola.com this repo is no longer maintained. we will take this feedback into considiration for our next major SDK version
