### ISSUE TITLE
SDK not available as standalone download. 

### ISSUE THREAD

**Issue by avolovoy** [taboola/taboola-ios#5]
Currently, the only way to get this seems to be CocoaPods - and not everybody uses that. Please provide Carthage support as well ability just to grab zip with the framework

**Comment by saschauereten** [comment]
I second that. We moved away from Cocoapods and would also like Carthage support.

**Comment by shlomiaf** [comment]
Hi @avolovoy  and @saschauereten thanks for your suggestion. we will definitely consider Carthage support.
meanwhile, you can download the framework as a zip file here: [https://s3-us-west-2.amazonaws.com/taboola-mobile-sdk/ios/1.6.8/TaboolaSDK.zip](https://s3-us-west-2.amazonaws.com/taboola-mobile-sdk/ios/1.6.8/TaboolaSDK.zip)

this link points to version #1.6.8 which is the latest.  update the version section the link for newer versions when they become available.

**Comment by omriariav** [comment]
@avolovoy - we will take a look and get back to you

**Comment by omriariav** [comment]
@avolovoy we have a new Carthage path: https://cdn.taboola.com/taboola-mobile-sdk/ios/carthage/TaboolaSDK.json
