### ISSUE TITLE
Taboola interrupt uiscrollview delegate

### ISSUE THREAD

**Issue by SiTianyu** [taboola/taboola-ios#8]
I have add taboola view programmatically in a uiscrollview. But after taboola fetchContent, it will interrupt uiscrollview delegate, I have to re-assign delegate to self view.
Is it a bug or maybe we should do something else?

**Comment by omriariav** [comment]
We have new documentation and SDK version. Our SDK, when using Feed is switching the scroll from the publisher app tinto the feed. See here: https://sdk.taboola.com This repo is no longer maintained
